// CrossPlatformTests.swift
// SaQura Swift Library Tests
// Copyright (c) 2025-2026 KyotoTech LLC. All rights reserved.
//
// These tests verify byte-level compatibility with the .NET SaQura Library.
// Test vectors should be generated by the .NET library and pasted here
// to verify that Swift can correctly decrypt .NET-encrypted messages.

import XCTest
@testable import SaQura

final class CrossPlatformTests: XCTestCase {

    // MARK: - Key Format Compatibility

    /// Verifies that Swift key headers match .NET format
    func testGen4KeyHeaderFormat() async throws {
        let (publicKey, privateKey) = try await Quantum.generateKeyPair(
            strength: .standard,
            generation: .gen4
        )

        // .NET PqGeneration4 header: [0x04][0x02 (Highest)]
        XCTAssertEqual(publicKey[0], 0x04, "Gen4 generation byte should be 0x04")
        XCTAssertEqual(publicKey[1], 0x02, "Gen4 always uses Highest strength (0x02)")
        XCTAssertEqual(privateKey[0], 0x04)
        XCTAssertEqual(privateKey[1], 0x02)
    }

    func testGen6KeyHeaderFormat() async throws {
        for strength in QuantumStrength.allCases {
            let (publicKey, _) = try await Quantum.generateKeyPair(
                strength: strength,
                generation: .gen6
            )

            // .NET QGeneration6 header: [0x06][Strength]
            XCTAssertEqual(publicKey[0], 0x06, "Gen6 generation byte should be 0x06")
            XCTAssertEqual(publicKey[1], strength.rawValue, "Gen6 strength should match \(strength)")
        }
    }

    func testGen2KeyHeaderFormat() async throws {
        let (publicKey, _) = try await Quantum.generateKeyPair(
            strength: .standard,
            generation: .gen2
        )

        // .NET PqGeneration2 header: [0x02][Strength]
        XCTAssertEqual(publicKey[0], 0x02, "Gen2 generation byte should be 0x02")
        XCTAssertEqual(publicKey[1], 0x00, "Gen2 standard strength should be 0x00")
    }

    func testGen5KeyHeaderFormat() async throws {
        let (publicKey, _) = try await Quantum.generateKeyPair(
            strength: .medium,
            generation: .gen5
        )

        // .NET QGeneration5 header: [0x05][Strength]
        XCTAssertEqual(publicKey[0], 0x05, "Gen5 generation byte should be 0x05")
        XCTAssertEqual(publicKey[1], 0x01, "Gen5 medium strength should be 0x01")
    }

    func testGen7KeyHeaderFormat() async throws {
        let (publicKey, _) = try await Quantum.generateKeyPair(
            strength: .standard,
            generation: .gen7
        )

        // .NET QGeneration7 header: [0x07][Strength][RSAKeyLen:4_LE]
        XCTAssertEqual(publicKey[0], 0x07, "Gen7 generation byte should be 0x07")
        XCTAssertEqual(publicKey[1], 0x00, "Gen7 standard strength should be 0x00")

        // RSA key length is stored as 4 bytes Little-Endian (matching .NET BitConverter)
        let rsaKeyLen = publicKey[2..<6].withUnsafeBytes { $0.loadUnaligned(as: UInt32.self).littleEndian }
        XCTAssertGreaterThan(rsaKeyLen, 0, "RSA key length should be positive")
        XCTAssertLessThan(rsaKeyLen, 2000, "RSA-4096 public key should be under 2000 bytes")
    }

    // MARK: - Wire Format Compatibility

    /// Verifies Gen4 encrypted message format matches .NET: [Nonce:12][CT][Tag:16]
    func testGen4EncryptedMessageFormat() async throws {
        let (publicKey, privateKey) = try await Quantum.generateKeyPair(
            strength: .standard,
            generation: .gen4
        )

        let (encapsulated, encrypted) = try await "Hello".encryptWithQuantum(publicKey: publicKey)

        // Encapsulated should be raw FrodoKEM-1344 ciphertext (no header)
        // FrodoKEM-1344-AES ciphertext is 21632 bytes
        XCTAssertEqual(encapsulated.count, 21632)

        // Encrypted: [Nonce:12][Ciphertext:N][Tag:16]
        // "Hello" = 5 bytes plaintext → 5 bytes ciphertext in GCM
        XCTAssertEqual(encrypted.count, 12 + 5 + 16) // 33 bytes total

        // Verify round-trip
        let decrypted = try await encrypted.decryptWithQuantum(privateKey: privateKey, secret: encapsulated)
        XCTAssertEqual(decrypted, "Hello")
    }

    /// Verifies Gen6 encrypted message format: [Salt:16][Nonce:12][CT][Tag:16]
    func testGen6EncryptedMessageFormat() async throws {
        let (publicKey, privateKey) = try await Quantum.generateKeyPair(
            strength: .standard,
            generation: .gen6
        )

        let (encapsulated, encrypted) = try await "Hello".encryptWithQuantum(publicKey: publicKey)

        // Encapsulated: raw FrodoKEM-640 ciphertext (9720 bytes for standard)
        XCTAssertEqual(encapsulated.count, 9720)

        // Encrypted: [Salt:16][Nonce:12][Ciphertext:5][Tag:16] = 49 bytes
        XCTAssertEqual(encrypted.count, 16 + 12 + 5 + 16)

        // Verify round-trip
        let decrypted = try await encrypted.decryptWithQuantum(privateKey: privateKey, secret: encapsulated)
        XCTAssertEqual(decrypted, "Hello")
    }

    /// Verifies Gen2 encrypted message format: [IV:16][CBC_CT][HMAC:32]
    func testGen2EncryptedMessageFormat() async throws {
        let (publicKey, privateKey) = try await Quantum.generateKeyPair(
            strength: .standard,
            generation: .gen2
        )

        let (_, encrypted) = try await "Hello".encryptWithQuantum(publicKey: publicKey)

        // Encrypted: [IV:16][CBC_Ciphertext:16 (1 block for 5 bytes + PKCS7)][HMAC:32]
        // AES-CBC with PKCS7: 5 bytes → 16 bytes (1 block)
        XCTAssertEqual(encrypted.count, 16 + 16 + 32) // 64 bytes

        // Verify IV is 16 bytes at start
        let iv = encrypted.prefix(16)
        XCTAssertEqual(iv.count, 16)

        // Verify HMAC is 32 bytes at end
        let hmac = encrypted.suffix(32)
        XCTAssertEqual(hmac.count, 32)
    }

    /// Verifies Gen5 encrypted message format: [Salt:32][IV:16][CBC_CT][HMAC:32]
    func testGen5EncryptedMessageFormat() async throws {
        let (publicKey, _) = try await Quantum.generateKeyPair(
            strength: .standard,
            generation: .gen5
        )

        let (_, encrypted) = try await "Hello".encryptWithQuantum(publicKey: publicKey)

        // Encrypted: [Salt:32][IV:16][CBC_CT:16][HMAC:32] = 96 bytes
        XCTAssertEqual(encrypted.count, 32 + 16 + 16 + 32)
    }

    /// Verifies Gen7 encrypted message format: [Salt:32][Nonce:12][CT][Tag:16]
    func testGen7EncryptedMessageFormat() async throws {
        let (publicKey, _) = try await Quantum.generateKeyPair(
            strength: .standard,
            generation: .gen7
        )

        let (encapsulated, encrypted) = try await "Hello".encryptWithQuantum(publicKey: publicKey)

        // Encapsulated: [RSAEncKeyLen:4_LE][RSAEncKey:512][FrodoCapsule]
        let rsaEncKeyLen = Int(encapsulated.prefix(4).withUnsafeBytes {
            $0.loadUnaligned(as: UInt32.self).littleEndian
        })
        XCTAssertEqual(rsaEncKeyLen, 512)

        // Encrypted: [Salt:32][Nonce:12][CT:5][Tag:16] = 65 bytes
        XCTAssertEqual(encrypted.count, 32 + 12 + 5 + 16)
    }

    // MARK: - Endianness Tests

    /// Verifies Little-Endian encoding matches .NET BitConverter
    func testLittleEndianEncoding() async throws {
        let (publicKey, _) = try await Quantum.generateKeyPair(
            strength: .standard,
            generation: .gen7
        )

        // RSA key length at offset 2..6 should be Little-Endian
        let rsaLenBytes = publicKey[2..<6]
        let rsaLenLE = rsaLenBytes.withUnsafeBytes { $0.loadUnaligned(as: UInt32.self).littleEndian }
        let rsaLenBE = rsaLenBytes.withUnsafeBytes { $0.loadUnaligned(as: UInt32.self).bigEndian }

        // The LE value should be reasonable (< 2000 for RSA-4096 public key)
        // The BE value would be enormous if the encoding is actually LE
        XCTAssertLessThan(rsaLenLE, 2000)
        XCTAssertNotEqual(rsaLenLE, rsaLenBE, "LE and BE should differ (validates endianness)")
    }

    /// Verifies combined format uses Little-Endian for length
    func testCombinedFormatLittleEndian() async throws {
        let (publicKey, privateKey) = try await Quantum.generateKeyPair(
            strength: .standard,
            generation: .gen6
        )

        let encrypted = try await "Test".encryptWithQuantumToBytes(publicKey: publicKey)

        // First 4 bytes should be secret length in LE
        let secretLenLE = encrypted.prefix(4).withUnsafeBytes {
            $0.loadUnaligned(as: UInt32.self).littleEndian
        }

        // FrodoKEM-640 ciphertext should be 9720 bytes
        XCTAssertEqual(secretLenLE, 9720)

        // Verify we can decrypt it
        let decrypted = try await encrypted.decryptWithQuantum(privateKey: privateKey)
        XCTAssertEqual(decrypted, "Test")
    }

    // MARK: - .NET Test Vector Placeholders
    // TODO: Generate test vectors from .NET and paste them here
    // Example format:
    //
    // func testDecryptGen4FromDotNet() async throws {
    //     let privateKey = Data(base64Encoded: "...")!
    //     let encapsulated = Data(base64Encoded: "...")!
    //     let encrypted = Data(base64Encoded: "...")!
    //     let expectedMessage = "Hello from .NET"
    //
    //     let decrypted = try await encrypted.decryptWithQuantum(
    //         privateKey: privateKey,
    //         secret: encapsulated
    //     )
    //     XCTAssertEqual(decrypted, expectedMessage)
    // }

    // MARK: - QuantumStrength Compatibility

    /// Verifies QuantumStrength raw values match .NET enum
    func testQuantumStrengthDotNetCompatibility() {
        // .NET: Standard=0, Medium=1, Highest=2
        XCTAssertEqual(QuantumStrength.standard.rawValue, 0)
        XCTAssertEqual(QuantumStrength.medium.rawValue, 1)
        XCTAssertEqual(QuantumStrength.highest.rawValue, 2)

        // Should only have 3 values (no Light/Maximum)
        XCTAssertEqual(QuantumStrength.allCases.count, 3)
        XCTAssertNil(QuantumStrength(rawValue: 3)) // No Maximum
    }
}
