// LicenseValidatorTests.swift
// SaQura Swift Library Tests
// Copyright (c) 2025-2026 KyotoTech LLC. All rights reserved.

import XCTest
@testable import SaQura

/// Cross-platform license-format coverage for Swift, parity with the
/// Kotlin `LicenseValidatorTest` suite. The fixture below is the
/// **same** `.lic` content the Kotlin tests use — produced by the
/// production .NET license server. If the Swift side fails to verify
/// what Kotlin accepts, the embedded public key or the signing-data
/// builder has drifted from .NET — a wire-format breakage that would
/// silently reject every customer activation.
///
/// Test-sweep 2026-05-12: this whole suite is NEW. Until this test sweep
/// the Swift library had **zero** tests covering `ApiLicense` or
/// `LicenseValidator` — silent breakage was previously possible without
/// any CI signal.
final class LicenseValidatorTests: XCTestCase {

    /// The Pro Distribution `.lic` content from
    /// `windows_test_app/SaQura_Pro_distribution.lic` — produced by the
    /// .NET license server, byte-for-byte the same fixture the Kotlin
    /// `LicenseValidatorTest` exercises.
    static let proDistributionJson = """
    {
      "id": "2dd7fdc5-9e98-4b85-9e25-1d21241c9963",
      "licenseKey": "PRO-VRY1-ELG4-YOPM-FFOR",
      "product": "KyotoTechCryptography",
      "tier": 3,
      "type": 1,
      "features": 0,
      "customer": {
        "id": "2dd7fdc5-9e98-4b85-9e25-1d21241c9963",
        "email": "test@example.com",
        "company": "",
        "name": ""
      },
      "issuedAt": "2025-12-31T06:51:41.7352260Z",
      "expiresAt": "2026-12-31T06:51:41.7352550Z",
      "hardwareId": "",
      "maxActivations": -1,
      "currentActivations": 0,
      "isRevoked": false,
      "signature": "I7mu6K3FUXfrzUa7aqxoEt5Ivf/ZyN3X5ZhlU5UgYNDR4cf2Ep2sT6pLzY5T6r2HRzuYqkL7Lcuc2k\\u002BCPbMDP0aC/hDr0v\\u002B7A33jOaFRD37\\u002B93B3pwiqQAag8NT56feYyMQbIzhNkDeBTv\\u002BNjYRCL6Hk5RgT4ASs4qXtcojL4vu8fbeSirWvxjlrnvgxP4gjYBqhbcu4H5rdZCAy2oc/wIy7eJQvWUzu/GaHoMqpd/fvg2ahmkllqaQVfl1YWL1Jme2us7AbwooV\\u002BDtwGN9brTXb80yIJzbv9jcGhG\\u002B9JSb800xkkSbBEg\\u002BHf2RBlm8xQfh4EVOIQnQ6gwai5dmlL\\u002Bcoh6tNc3ssbWh5DeJzCRqEHXfKisrz2VttRrjlmmXxZr1vk8v\\u002BMgeTKSfdZQgh4Qx/7XwMEcvUZDy3L0JEZMhsUh7lOpXOWYyGeIl7bx00ozwY0Ynd3wPvccc9/kF1466\\u002BeQWZsU5mwmGeT0mqdE9lxHNglNdJBoMiBeYQqr3qQjUgD/2xf3Q8m80a7IyBCKZQ3A4h//yGRYJNBfW6KvOQrRR42U07XBsB\\u002BXXA5wBIC97dtC8i1Zt6LHSsOf5T51JJGfmELoj1Ib16Jd0IXShKKstbBYD/ext8E4cZVGTR3/h49kL4\\u002BwIKHs73CowsNTQdSrEgOsTKnYywZTjrbjk=",
      "metadata": {
        "licenseType": "distribution",
        "autoGenerated": "true"
      }
    }
    """

    // MARK: - deserialization

    func testDeserializeProDistributionFixture() {
        let license = LicenseValidator.deserializeLicense(Self.proDistributionJson)
        XCTAssertNotNil(license)
        XCTAssertEqual(license?.id.uuidString.lowercased(), "2dd7fdc5-9e98-4b85-9e25-1d21241c9963")
        XCTAssertEqual(license?.licenseKey, "PRO-VRY1-ELG4-YOPM-FFOR")
        XCTAssertEqual(license?.product, "KyotoTechCryptography")
        XCTAssertEqual(license?.tier, .pro)
        XCTAssertEqual(license?.type, .distribution)
        XCTAssertEqual(license?.maxActivations, -1)
        XCTAssertEqual(license?.customer.email, "test@example.com")
    }

    func testDeserializeBlankReturnsNil() {
        XCTAssertNil(LicenseValidator.deserializeLicense(""))
        XCTAssertNil(LicenseValidator.deserializeLicense("   "))
    }

    func testDeserializeMalformedReturnsNil() {
        XCTAssertNil(LicenseValidator.deserializeLicense("not-json"))
        XCTAssertNil(LicenseValidator.deserializeLicense("{"))
    }

    /// **Cross-platform parity assertion.** The signing string Swift
    /// constructs from this fixture must produce the same bytes the
    /// .NET server signed; otherwise `validateLicense` would fail with
    /// "Invalid license signature".
    func testValidateProDistributionFixtureSignatureVerifies() {
        let license = LicenseValidator.deserializeLicense(Self.proDistributionJson)!
        let result = LicenseValidator.validateLicense(license, checkHardware: false)
        XCTAssertTrue(result.isValid, "Expected valid; got errorMessage: \(result.errorMessage ?? "nil")")
        XCTAssertEqual(result.tier, .pro)
        XCTAssertTrue(result.isDistributionLicense)
    }

    /// Reconstruct a LicenseInfo with `isRevoked` flipped. isRevoked is
    /// NOT in the signing-data string, so the signature still verifies
    /// and we reach the revocation check.
    private func withRevoked(_ original: LicenseInfo, revoked: Bool) -> LicenseInfo {
        return LicenseInfo(
            id: original.id,
            licenseKey: original.licenseKey,
            product: original.product,
            tier: original.tier,
            type: original.type,
            parentLicenseId: original.parentLicenseId,
            features: original.features,
            customer: original.customer,
            issuedAt: original.issuedAt,
            expiresAt: original.expiresAt,
            hardwareId: original.hardwareId,
            maxActivations: original.maxActivations,
            currentActivations: original.currentActivations,
            isRevoked: revoked,
            signature: original.signature,
            metadata: original.metadata,
            serverValidated: original.serverValidated,
            issuedAtRaw: original.issuedAtRaw,
            expiresAtRaw: original.expiresAtRaw
        )
    }

    func testValidateRejectsRevokedLicense() {
        let license = LicenseValidator.deserializeLicense(Self.proDistributionJson)!
        let revoked = withRevoked(license, revoked: true)
        let result = LicenseValidator.validateLicense(revoked, checkHardware: false)
        XCTAssertFalse(result.isValid)
        XCTAssertEqual(result.errorMessage, "License has been revoked")
    }

    private func rewriteSignature(_ original: LicenseInfo, to newSig: String) -> LicenseInfo {
        return LicenseInfo(
            id: original.id,
            licenseKey: original.licenseKey,
            product: original.product,
            tier: original.tier,
            type: original.type,
            parentLicenseId: original.parentLicenseId,
            features: original.features,
            customer: original.customer,
            issuedAt: original.issuedAt,
            expiresAt: original.expiresAt,
            hardwareId: original.hardwareId,
            maxActivations: original.maxActivations,
            currentActivations: original.currentActivations,
            isRevoked: original.isRevoked,
            signature: newSig,
            metadata: original.metadata,
            serverValidated: original.serverValidated,
            // Critical: preserve the raw JSON date strings — without them
            // the signing-data builder falls back to a re-rendered date
            // format that doesn't match what the .NET server signed.
            issuedAtRaw: original.issuedAtRaw,
            expiresAtRaw: original.expiresAtRaw
        )
    }

    func testValidateRejectsTamperedSignature() {
        let license = LicenseValidator.deserializeLicense(Self.proDistributionJson)!
        // Flip the first character of the base64 signature.
        let tampered = rewriteSignature(license, to: "X" + license.signature.dropFirst())
        let result = LicenseValidator.validateLicense(tampered, checkHardware: false)
        XCTAssertFalse(result.isValid)
        XCTAssertEqual(result.errorMessage, "Invalid license signature")
    }

    func testValidateRejectsEmptySignature() {
        let license = LicenseValidator.deserializeLicense(Self.proDistributionJson)!
        let stripped = rewriteSignature(license, to: "")
        let result = LicenseValidator.validateLicense(stripped, checkHardware: false)
        XCTAssertFalse(result.isValid)
    }

    // MARK: - license-key format

    func testValidateLicenseKeyFormatAcceptsRealKey() {
        XCTAssertTrue(LicenseValidator.validateLicenseKeyFormat("PRO-VRY1-ELG4-YOPM-FFOR"))
    }

    func testValidateLicenseKeyFormatRejectsBadChecksum() {
        XCTAssertFalse(LicenseValidator.validateLicenseKeyFormat("PRO-VRY1-ELG4-YOPM-AAAA"))
    }

    func testValidateLicenseKeyFormatRejectsWrongSegmentCount() {
        XCTAssertFalse(LicenseValidator.validateLicenseKeyFormat("PRO-VRY1-ELG4"))
        XCTAssertFalse(LicenseValidator.validateLicenseKeyFormat("PRO-VRY1-ELG4-YOPM-FFOR-EXTRA"))
    }

    func testValidateLicenseKeyFormatRejectsNonAlphanumeric() {
        XCTAssertFalse(LicenseValidator.validateLicenseKeyFormat("PRO-VRY!-ELG4-YOPM-FFOR"))
    }

    func testValidateLicenseKeyFormatRejectsBlank() {
        XCTAssertFalse(LicenseValidator.validateLicenseKeyFormat(""))
        XCTAssertFalse(LicenseValidator.validateLicenseKeyFormat("   "))
    }

    // MARK: - INTERNAL tier bypass

    func testValidateInternalTierBypassesAllChecks() {
        let internalLicense = LicenseInfo(
            id: UUID(),
            licenseKey: "INTERNAL",
            product: "SaQura",
            tier: LicenseTier.internal,
            type: LicenseType.standard,
            parentLicenseId: nil,
            features: LicenseFeatures.none,
            customer: CustomerInfo(id: UUID(), email: "internal@saqura.io", company: nil, name: nil),
            issuedAt: Date(),
            expiresAt: Date().addingTimeInterval(86400),
            hardwareId: "",
            maxActivations: Int.max,
            currentActivations: 0,
            isRevoked: false,
            signature: "INTERNAL", // bogus — INTERNAL bypasses signature check
            metadata: nil,
            serverValidated: false
        )
        let result = LicenseValidator.validateLicense(internalLicense)
        XCTAssertTrue(result.isValid)
        XCTAssertEqual(result.tier, LicenseTier.internal)
        XCTAssertEqual(result.features, LicenseFeatures.all)
        XCTAssertEqual(result.daysRemaining, Int.max)
    }

    // MARK: - effectiveFeatures tier-fallback (cross-platform parity)
    //
    // The .NET license server produces .lic files with `features: 0` for
    // tier-based licenses (the tier field carries the entitlement; the
    // explicit bitmask is reserved for ad-hoc feature combinations). Both
    // .NET (`LicensingService.EnabledFeatures`) and Kotlin
    // (`LicenseInfo.effectiveFeatures`) fall back to the tier's default
    // feature set when the explicit bitmask is empty. v1.0.8 surfaced a
    // Swift-side parity gap: the bare `features` field was checked
    // directly, so customers with `features: 0` licenses saw every gate
    // closed regardless of tier. These tests pin the fallback contract.

    private static func licenseInfoStub(
        tier: LicenseTier,
        features: LicenseFeatures
    ) -> LicenseInfo {
        return LicenseInfo(
            id: UUID(),
            licenseKey: "TEST",
            product: "SaQura",
            tier: tier,
            type: .standard,
            parentLicenseId: nil,
            features: features,
            customer: CustomerInfo(id: UUID(), email: "test@example.com", company: nil, name: nil),
            issuedAt: Date(),
            expiresAt: Date().addingTimeInterval(86400),
            hardwareId: "",
            maxActivations: 1,
            currentActivations: 0,
            isRevoked: false,
            signature: "",
            metadata: nil
        )
    }

    func testEffectiveFeaturesFallsBackToTierWhenExplicitIsZero() {
        let pro = Self.licenseInfoStub(tier: .pro, features: LicenseFeatures(rawValue: 0))
        let effective = pro.effectiveFeatures
        XCTAssertTrue(effective.contains(.rsa))
        XCTAssertTrue(effective.contains(.aes))
        XCTAssertTrue(effective.contains(.quantum))
        XCTAssertTrue(effective.contains(.passwordHashing))
        XCTAssertTrue(effective.contains(.noWatermark))
        XCTAssertFalse(effective.contains(.prioritySupport)) // pro != enterprise
    }

    func testEffectiveFeaturesUsesExplicitWhenNonzero() {
        // explicit bitmask wins even if it's narrower than the tier default
        let pro = Self.licenseInfoStub(tier: .pro, features: [.rsa, .passwordHashing])
        let effective = pro.effectiveFeatures
        XCTAssertTrue(effective.contains(.rsa))
        XCTAssertTrue(effective.contains(.passwordHashing))
        XCTAssertFalse(effective.contains(.aes))      // would be Pro-default but explicit overrides
        XCTAssertFalse(effective.contains(.quantum))
        XCTAssertFalse(effective.contains(.noWatermark))
    }

    func testEffectiveFeaturesFreeTierFallbackIsNone() {
        let free = Self.licenseInfoStub(tier: .free, features: LicenseFeatures(rawValue: 0))
        XCTAssertEqual(free.effectiveFeatures.rawValue, 0)
    }

    func testEffectiveFeaturesEnterpriseTierFallbackIsAll() {
        let ent = Self.licenseInfoStub(tier: .enterprise, features: LicenseFeatures(rawValue: 0))
        XCTAssertEqual(ent.effectiveFeatures, LicenseFeatures.all)
    }

    /// Integration check against the same `proDistributionJson` fixture
    /// the deserialization tests use — that JSON has `features: 0` +
    /// `tier: 3` (Pro), the exact shape the .NET server emits in
    /// production. Before the v1.0.8 fix this test would have failed
    /// `XCTAssertTrue(effective.contains(.aes))` because `features` was
    /// read directly.
    func testProDistributionFixtureYieldsProFeaturesViaFallback() throws {
        let license = try XCTUnwrap(LicenseValidator.deserializeLicense(Self.proDistributionJson))
        XCTAssertEqual(license.features.rawValue, 0, "fixture preserves explicit features:0 on disk")
        let effective = license.effectiveFeatures
        XCTAssertTrue(effective.contains(.aes))
        XCTAssertTrue(effective.contains(.rsa))
        XCTAssertTrue(effective.contains(.quantum))
        XCTAssertTrue(effective.contains(.passwordHashing))
        XCTAssertTrue(effective.contains(.noWatermark))
    }
}
